FROM python:3.11-slim
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY services /app/services
ENV PYTHONPATH=/app
CMD sh -c "celery -A services.worker.tasks.celery worker --loglevel=INFO --without-mingle --without-gossip --pool=solo & uvicorn services.worker.server:app --host 0.0.0.0 --port 8001 && wait"