events {}
http {
  server {
    listen 80;
    location /audio/ {
      alias /var/www/audio/;
      autoindex on;
      add_header Access-Control-Allow-Origin *;
    }
    location / {
      proxy_pass http://api:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
